### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by thipokKub** [phizaz/chula_rl#1]
Syntax Error in "trainer.py", line 20
```
n_eval_interaction: int = 1_000):
SyntaxError: invalid syntax
```

**Comment by konpatp** [comment]
@thipokKub Is it possible that you're using python < 3.6?

**Comment by thipokKub** [comment]
Yes, I am using python 3.5.5
For me, after I fix that line, it worked like charm

**Comment by konpatp** [comment]
@thipokKub Could you share how did you fix it?

**Comment by thipokKub** [comment]
I just change
```
n_eval_interaction: int = 1_000
```
to
```
n_eval_interaction: int = 1000
```

**Comment by konpatp** [comment]
@thipokKub  Oh, the under scroll number literals were introduced in Python 3.6. Unfortunately 😓.
https://www.python.org/dev/peps/pep-0515/
